In [39]:
import numpy as np
import math
from scipy import stats

Задача 1

Даны значения величины заработной платы заемщиков банка (salary) и значения их поведенческого кредитного скоринга (scoring):

salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

Используя только встроенные питоновские функции и структуры данных (т.е. без библиотек numpy, pandas и др.) найдите:
1. ковариацию (смещённую и несмещённую) этих двух величин,
2. коэффициент корреляции Пирсона.

Можно затем посчитать те же значения с использованием библиотек, чтобы проверить себя.


In [33]:
salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

salary_mean = sum(salary) / len(salary)
scoring_mean = sum(scoring) / len(scoring)
salary_mean, scoring_mean

cov_s = 0
cov_ns = 0
for i in range(0, len(salary)):
    cov_s = cov_s + ((salary[i] - salary_mean) * (scoring[i] - scoring_mean))
    cov_ns = cov_ns + ((salary[i] - salary_mean) * (scoring[i] - scoring_mean))

cov_s = cov_s / len(salary)
cov_ns = cov_ns / (len(salary)-1)
cov_s, cov_ns

(9157.84, 10175.377777777778)

In [32]:
salary = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
scoring = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

np.cov(salary, scoring, ddof=0), np.cov(salary, scoring, ddof=1)

(array([[ 3494.64,  9157.84],
        [ 9157.84, 30468.89]]),
 array([[ 3882.93333333, 10175.37777778],
        [10175.37777778, 33854.32222222]]))

In [31]:
salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

salary_mean = sum(salary) / len(salary)
scoring_mean = sum(scoring) / len(scoring)

salary_1 = 0
scoring_1 = 0
for i in range(0,len(salary)):
    salary_1 = salary_1 + (salary[i]-salary_mean)**2
    scoring_1 = scoring_1 + (scoring[i]-scoring_mean)**2
salary_1 = salary_1 / len(salary)
salary_std = math.sqrt(salary_1)
scoring_1 = scoring_1 / len(scoring)
scoring_std = math.sqrt(scoring_1)

salary_std, scoring_std

corr = cov_s / (salary_std * scoring_std)
corr

0.8874900920739162

In [30]:
salary = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
scoring = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

np.corrcoef(salary, scoring)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Задача 2

Проведите тест на значимость коэффициента корреляции Пирсона, найденного в предыдущей задаче. Что для этого нужно знать:
* Нулевая гипотеза: реальный коэффициент корреляции равен 0. Альтернативная гипотеза двухсторонняя.
* Статистика: t = r * sqrt(n - 2) / sqrt(1 - r ** 2), где r - коэффициент корреляции Пирсона, посчитанный по выборке.
* В предположении верности нулевой гипотезы эта статистика имеет распределение Стьюдента с параметром df = n - 2.


In [56]:
t = corr * math.sqrt(len(salary) - 2) / math.sqrt(1 - corr ** 2)
t          # 5.447168150485575

n = len(salary)
t1 = stats.t.ppf(0.05 / 2, df=n - 1)
t2 = stats.t.ppf(1 - 0.05 / 2, df=n - 1)
t1, t2     # -2.262157162740992, 2.2621571627409915

# Значение статистики попало в критическую область, значит, гипотеза не подтвердилась.

p_left = stats.t.cdf(t, df=n - 2)
p_right = 1 - stats.t.cdf(t, df=n - 2)

pvalue = 2 * min(p_left, p_right)

pvalue          # P-значение для данного теста 0.0006107546587257318


0.0006107546587257318

Задача 3

Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111

Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [59]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
n = iq.size
std = iq.std()
D = std**2
mean = iq.mean()
p = 0.95
alpha = 1-p

# Квантили:
t1 = stats.norm.ppf(alpha/2)
t2 = stats.norm.ppf(1 - alpha/2)
t1, t2            # -1.959963984540054, 1.959963984540054

# Доверительный интервал:
x1 = (mean + t1 * std / np.sqrt(n))
x2 = (mean + t2 * std / np.sqrt(n))
x1, x2            # (111.89926122656924, 124.30073877343075)

(111.89926122656924, 124.30073877343075)

Задача 4

Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики и напишите ее 
в комментарии к Практическому заданию.

In [ ]:
Тема и датасет предполагаемого проекта в файле:
Math_stat_project.ipynb