In [52]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

1. Найти с помощью NumPy SVD для матрицы

In [53]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [54]:
# A=UDV(t)
U, S, Vt = np.linalg.svd(A)
print(np.dot(U.T, U))
print()
print(np.dot(Vt.T, Vt))
print()

[[ 1.  0. -0.  0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1. -0. -0.]
 [ 0.  0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]

[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]



In [55]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = S
D

array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [56]:
print('A = ')
A

A = 


array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [57]:
print('U = ')
U

U = 


array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])

In [58]:
print('D = ')
D

D = 


array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [59]:
print('V(t) = ')
Vt

V(t) = 


array([[ 0.07,  0.72,  0.69],
       [-0.37,  0.67, -0.65],
       [-0.93, -0.21,  0.31]])

In [60]:
print ('UDV(t) = ')
np.dot(np.dot(U, D), Vt)

UDV(t) = 


array([[ 1.,  2.,  0.],
       [ 0., -0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [-0.,  1., -0.]])

In [61]:
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

2. Для матрицы из предыдущего задания найти:

а) евклидову норму;

б) норму Фробениуса.

In [64]:
S
# евклидова норма = 8.82
# максимальное сингулярное число

array([8.82, 6.14, 2.53])

In [ ]:
 # нормa Фробениуса = sqrt(8.82**2 + 6.14**2 + 2.53**2) = 11.04