In [1]:
import numpy as np

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:
а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;
б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;
в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;
г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4.

In [9]:
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
B = A
A, B
# A*B и B*A невозможно, т.к. нет соответствия столбцов первой матрицы строкам 2 матрицы

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]))

In [14]:
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 1]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6]])
A, B
# B*A невозможно, т.к. нет соответствия столбцов первой матрицы строкам 2 матрицы

(array([[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 1]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6]]))

In [19]:
# A*B
# 1*1 + 2*4 + 3*7 + 4*1 + 5*4    1*2 + 2*5 + 3*8 + 4*2 + 5*5   1*3 + 2*6 + 3*9 + 4*3 + 5*6  
  6*1 + 7*4 + 8*7 + 9*1 + 1*4    6*2 + 7*5 + 8*8 + 9*2 + 1*5   6*3 + 7*6 + 8*9 + 9*3 + 1*6 
# размерность 2*3
np.dot(A, B)

array([[ 54,  69,  84],
       [103, 134, 165]])

In [24]:
A = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]])
B = np.array([[1, 2, 1, 2, 1, 2, 1, 2], [1, 2, 1, 2, 1, 2, 1, 2], [1, 2, 1, 2, 1, 2, 1, 2]])
# B*A невозможно, т.к. нет соответствия столбцов первой матрицы строкам 2 матрицы
A, B, np.dot(A, B)
# размерность 8*8

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 2, 1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2, 1, 2]]),
 array([[ 6, 12,  6, 12,  6, 12,  6, 12],
        [ 6, 12,  6, 12,  6, 12,  6, 12],
        [ 6, 12,  6, 12,  6, 12,  6, 12],
        [ 6, 12,  6, 12,  6, 12,  6, 12],
        [ 6, 12,  6, 12,  6, 12,  6, 12],
        [ 6, 12,  6, 12,  6, 12,  6, 12],
        [ 6, 12,  6, 12,  6, 12,  6, 12],
        [ 6, 12,  6, 12,  6, 12,  6, 12]]))

In [26]:
A = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4],])
B = np.array([[5, 6, 7, 8], [5, 6, 7, 8], [5, 6, 7, 8], [5, 6, 7, 8],])
A, B, np.dot(A, B), np.dot(B, A)
# размерность 4*4 в обоих случаях, но результирующие матрицы разные

(array([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]),
 array([[5, 6, 7, 8],
        [5, 6, 7, 8],
        [5, 6, 7, 8],
        [5, 6, 7, 8]]),
 array([[50, 60, 70, 80],
        [50, 60, 70, 80],
        [50, 60, 70, 80],
        [50, 60, 70, 80]]),
 array([[ 26,  52,  78, 104],
        [ 26,  52,  78, 104],
        [ 26,  52,  78, 104],
        [ 26,  52,  78, 104]]))

2. Найти сумму и произведение матриц  A  и  B. 

In [29]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
# 1+4   -2-1
# 3+0   0+5

# 1*4 + -2*0     1*-1 + -2*5     
# 3*4 + 0*0      3*-1 + 0*5

A, B, A+B, np.dot(A, B), np.dot(B, A)

(array([[ 1, -2],
        [ 3,  0]]),
 array([[ 4, -1],
        [ 0,  5]]),
 array([[ 5, -3],
        [ 3,  5]]),
 array([[  4, -11],
        [ 12,  -3]]),
 array([[ 1, -8],
        [15,  0]]))

3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3A−2B+4C  для матриц  A,  B,  C. 

In [43]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

# 3A  [3, 21], [9,-18] 
# 2B  [0, 10], [4, -2]
# 4C  [8, -16], [4, 4]

# [3-0+8, 21-10-16], [9+4-4, -18+2+4]
# [11, -5], [9, -12]

A, B, C, (3*A) - (2*B) + (4*C)


(array([[ 1,  7],
        [ 3, -6]]),
 array([[ 0,  5],
        [ 2, -1]]),
 array([[ 2, -4],
        [ 1,  1]]),
 array([[ 11,  -5],
        [  9, -12]]))

4. Дана матрица  A. Вычислить  AAT  и  ATA .

In [46]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A, A.T, np.dot(A, A.T), np.dot(A.T, A)

(array([[ 4,  1],
        [ 5, -2],
        [ 2,  3]]),
 array([[ 4,  5,  2],
        [ 1, -2,  3]]),
 array([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]]),
 array([[45,  0],
        [ 0, 14]]))

5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

1. Вычислить определитель:

In [57]:
A = np.array([['sin(x)', '-cos(x)'], ['cos(x)', 'sin(x)']])
# (sin(x))**2 + (cos(x))**2 = 1

B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
# Определитель матрицы треугольного вида равен произведению элементов, стоящих на ее главной диагонали
# 4*5*9 = 180

C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 1*(5*9 - 8*6) - 2*(4*9 - 7*6) + 3*(4*8 - 5*7) = -3 + 12 - 9 = 0

A, B, C, np.linalg.det(B), np.linalg.det(C)

(array([['sin(x)', '-cos(x)'],
        ['cos(x)', 'sin(x)']], dtype='<U7'),
 array([[4, 2, 3],
        [0, 5, 1],
        [0, 0, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 180.0,
 0.0)

2. Определитель матрицы  A  равен  4 . Найти:
а)  det(A2) ;
б)  det(AT) ;
в)  det(2A) .

In [65]:
# а) 4**2 = 16

# б) 4     Определитель транспонированной матрицы равен определителю исходной

# в) 2*кол-во строк*4   Умножение строки или столбца матрицы на число  λ  приведет к умножению определителя матрицы на то же число


3. Доказать, что матрица A вырожденная.

In [67]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
# Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.
# Если первую строку умножить на -2, то получим 2 строку, значит определитель равен 0
A

array([[ -2,   7,  -3],
       [  4, -14,   6],
       [ -3,   7,  13]])

4. Найти ранг матрицы A, B:

In [70]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
# если к 1 строке прибавить 2 строку, то получим 3 строку, т.о. её можно отбросить = ранг равен 2

B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
# если к 1 строке прибавить 2 строку, то получим 3 строку, т.о. её можно отбросить = ранг равен 3

A, B, np.linalg.matrix_rank(A), np.linalg.matrix_rank(B)

(array([[1, 2, 3],
        [1, 1, 1],
        [2, 3, 4]]),
 array([[0, 0, 2, 1],
        [0, 0, 2, 2],
        [0, 0, 4, 3],
        [2, 3, 5, 6]]),
 2,
 3)