In [1]:
import numpy as np

1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

In [3]:
A = np.array([[-1, -6], [2, 6]])
# (-1−λ)(6−λ)−(-6)⋅2=0
# -6+λ-6λ +λ**2)=-12
# λ**2-5λ=-6
# λ1 = 2  λ2 = 3 
# 1) 
# -1*x1-6*x2=2*x1   
# 2*x1+6*x2=2*x2
# x1=-2*x2     vector (1, -2)
#2)
# -1*x1-6*x2=3*x1
# 2*x1+6*x2=3*x2
#  x1=-3/2 *x2    vector (1, -3/2)
A

array([[-1, -6],
       [ 2,  6]])

2. Дан оператор поворота на 180 градусов, задаваемый матрицей. Показать, что любой вектор является для него собственным.

In [4]:
A = np.array([[-1, 0], [0, -1]])
# (-1−λ)(-1-λ)=0
# λ = -1
# -x1 = -x1,  -x2=-x2 -> получилось тождество, поэтому любые значения  (x1, x2) подходят
A


array([[-1,  0],
       [ 0, -1]])

3. Пусть линейный оператор задан матрицей A. Установить, является ли вектор  x=(1,1)  собственным вектором этого линейного оператора.

In [5]:
A = np.array([[1, 1], [-1, 3]])
Ax = λx
# 1*1 + 1*1 = 2      
# -1*1 + 3*1 = 2      

# является собственным вектором. Лямбда = 2

array([[ 1,  1],
       [-1,  3]])

4. Пусть линейный оператор задан матрицей. Установить, является ли вектор  x=(3,−3,−4)  собственным вектором этого линейного оператора.

In [7]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
A

# 0*3+3*(-3)+ 0*(-4) = -9
# 3*3+0*(-3)+ 0*(-4) = 9
# 0*3+0*(-3)+3*(-4) = -12

# не является собственным вектором.

array([[0, 3, 0],
       [3, 0, 0],
       [0, 0, 3]])